(ns euler1)
(def items (range 1 1000))
(defn isRemainder [a] (= 0 a))
(defn isRemainderOfThree [x] (isRemainder (rem x 3)))
(defn isRemainderOfFive [x] (isRemainder (rem x 5)))
(defn fiveOrThreeRemainder [x] (or (isRemainderOfFive x) (isRemainderOfThree x)))
(def matchingItems (filter fiveOrThreeRemainder items))
(def sum (reduce + matchingItems))
(println sum)